### ISSUE TITLE
module NewRelic.Transaction.Plug is not avalable

### ISSUE THREAD

**Issue by roynalnaruto** [binaryseed/new_relic_phoenix#12]
I added the following dependencies in my `mix.exs`:
```
{:new_relic_agent, "~> 1.9.11"},
{:new_relic_phoenix, "~> 0.2.0"}
```

I added the following in my `config.exs`:
```
config :my_umbrella_api, MyUmbrellaApiWeb.Endpoint,
  http: [port: 4001],
  debug_errors: true,
  code_reloader: false,
  check_origin: false,
  server: true,
  watchers: [],
  instrumenters: [NewRelic.Phoenix.Instrumenter]

config :new_relic_agent,
  app_name: "Local test for API",
  license_key: "my_valid_key"
```

I have a phoenix endpoint that plugs a router module
```
defmodule MyUmbrellaApiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :my_umbrella_api
  use Absinthe.Phoenix.Endpoint
  use NewRelic.Phoenix.Transaction

  # some code

  plug MyUmbrellaApiWeb.Router
end
```

The router module looks like this:
```
defmodule MyUmbrellaApiWeb.Router do
  use MyUmbrellaApiWeb, :router

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :api

    forward "/graphiql", Absinthe.Plug.GraphiQL,
      schema: MyUmbrellaApiWeb.Schema,
      socket: MyUmbrellaApiWeb.SomeSocket,
      interface: :simple,
      context: %{pubsub: MyUmbrellaApiWeb.Endpoint}

    forward "/graphql", Absinthe.Plug, schema: MyUmbrellaApiWeb.Schema
  end

  forward "/api", MyUmbrellaApiWeb.Router.API
end
```

In the `MyUmbrellaApiWeb.Router.API`, I have the following:
```
defmodule MyUmbrellaApiWeb.Router.API do
  import Plug.Conn
  use Plug.Router
  use NewRelic.Transaction

  # some code
end
```

### Observed Behavior
When I make a request to `/api/health`, which is just a simple endpoint, I get the following error:
```
11:54:28.376 [error] #PID<0.2671.0> running MyUmbrellaApiWeb.Endpoint (connection #PID<0.2670.0>, stream id 1) terminated
Server: localhost:4001 (http)
Request: GET /api/health
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function NewRelic.Transaction.Plug.init/1 is undefined (module NewRelic.Transaction.Plug is not available)
        NewRelic.Transaction.Plug.init([])
        (my_umbrella_api) lib/my_umbrella_api_web/endpoint.ex:1: MyUmbrellaApiWeb.Endpoint.plug_builder_call/2
        (my_umbrella_api) lib/plug/debugger.ex:122: MyUmbrellaApiWeb.Endpoint."call (overridable 3)"/2
        (my_umbrella_api) lib/my_umbrella_api_web/endpoint.ex:1: MyUmbrellaApiWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:40: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /home/rohit/Develop/my_umbrella/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /home/rohit/Develop/my_umbrella/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /home/rohit/Develop/my_umbrella/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

What am I missing here?

**Comment by binaryseed** [comment]
The agent version `"~> 1.9.11"` will pin the agent to nothing higher than `1.9` - the current version is `1.19.2`. I suggest upgrading the agent!
